### PR TITLE
Update builder ubuntu version

### PR DESCRIPTION
**Pull request by RomainNaour**

### CODE REVIEW

**Comment by tpetazzoni** [comment]
I have applied the update of the Ubuntu distro from artful to disco.

**Comment by RomainNaour** [comment]
Hi Thomas,

Sorry but it's too late for Disco [1].

Maybe we can upgrade to Focal (the upcoming 20.04) Docker image [1] or use Bionic ?

[1] https://lists.ubuntu.com/archives/ubuntu-announce/2020-January/000253.html
[2] https://hub.docker.com/_/ubuntu/

**Comment by RomainNaour** [comment]
It seems that buildroot-toolchains git [1] is not up-to-date. 

[1] https://github.com/bootlin/buildroot-toolchains

**Comment by tpetazzoni** [comment]
So for the change from Debian Squeeze/Jessie to Stretch, I've decided to keep using Debian Jessie for now, see https://github.com/bootlin/toolchains-builder/commit/dee4969ca5852158a89160266ae9c25756e3995a.

For the kernel headers of stable toolchains, I've opted to use 4.4.x instead of 4.14.x, see https://github.com/bootlin/toolchains-builder/commit/aee953bab112235344cda2837084c35356f984b4

**Pull request closed without merging**
